### PR TITLE
Adjust plot in html

### PR DESCRIPTION
**Pull request by mortonjt**
This partially adjusts #8 

About the hovertool, I'm not sure how to adjust it.  Note that it toggles between the left and right edge, depending on where on the plot the point is.

Furthermore, I actually don't agree with the choice to use the raw sequence as the OTU id.  I raised this issue a while ago [here](https://github.com/biocore/deblur/issues/65) . Using raw sequence identifiers is seriously not practical for everyday use, this will need to change in future OTU picking methods.

CCed @wasade @josenavas @amnona

### CODE REVIEW

**Comment by gregcaporaso** [comment]
> Using raw sequence identifiers is seriously not practical for everyday 

I'm with you on this now, I've been going back and forth on this. It's going to really hard for every visualization to deal with this. I'm likely going to switch this to be md5 of sequences in q2-dada2. @wasade has some ideas about lossless transformations that we could use, which I think could be really cool (in which case md5 would be our stopgap while we figure something cooler out).

**Comment by amnona** [comment]
Personally, i prefer having the raw sequence identifier as it contains the
complete information (MD5 can have collisions) and can be easily
blasted/etc :)
for tooltips, you can show the taxonomy/md5 of data, but i think the
identifier should be the original sequence (this is what we do with deblur)

**Comment by gregcaporaso** [comment]
Let's discuss this [here](https://github.com/benjjneb/q2-dada2/issues/4) - this conversation is happening in multiple places.

**Comment by gregcaporaso** [comment]
I tested this locally and it works well for me.

**Pull request merged**
